### ISSUE TITLE
Don't push changes to .idea and gradle files

### ISSUE THREAD

**Issue by bitgenie** [flippindylan/CS245_AndroidApp#3]
It messes with everyone else's Android Studio so make sure to uncheck them when commiting

**Comment by dmnuggins** [comment]
I'll double check that. My bad.

**Comment by dmnuggins** [comment]
Reverted both merges from my branch. Check if the app works now on your end.

**Comment by dmnuggins** [comment]
Both merges from music_settings branch reverted. Issue resolved.
