### ISSUE TITLE
 java.lang.RuntimeException: Unable to pause activity 

### ISSUE THREAD

**Issue by bitgenie** [flippindylan/CS245_AndroidApp#4]
Caused by: java.lang.SecurityException: Permission Denial: getTasks() from pid=2311, uid=10058 requires android.permission.GET_TASKS

On line 75 in StartActivity
List<ActivityManager.RunningTaskInfo> taskInfo = am.getRunningTasks(1);

I get this error after inputting a number in StartActivity

**Comment by dmnuggins** [comment]
I'm reverting my changes. To get rid of the mods to the idea and gradle files.

**Comment by dmnuggins** [comment]
Both merges from music_settings branch reverted. Issue resolved.
